# Generated by Django 5.0.3 on 2024-03-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('film_name', models.CharField(help_text='Введите название фильма', max_length=200)),
                ('film_description', models.TextField(help_text='Введите описание фильма', max_length=99999)),
                ('film_release_date', models.DateField(default=True, help_text='Дата выпуска фильма')),
                ('film_preview_image', models.ImageField(help_text='Превью для фильма', upload_to='uploads/preview/')),
                ('film_videofile', models.FileField(help_text='Собственно, сам фильм', upload_to='uploads/films/')),
            ],
        ),
    ]
